apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokeapi-instance1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pokeapi-instance1
  template:
    metadata:
      labels:
        app: pokeapi-instance1
    spec:
      containers:
      - name: pokeapi
        image: pokeapi:0.1
        ports:
        - containerPort:3000
        env:
        - name: POKEDEX_NAME
          value: "Instance1Pokedex"
        - name: POKEDEX_START_NUMBER
          value: "1"
        - name: POKEDEX_END_NUMBER
          value: "151"

