apiVersion: v1
kind: Service
metadata:
  name: pokeapi-instance1-service
spec:
  selector:
    app: pokeapi-instance1
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
