apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokeapi-instance2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokeapi-instance2
  template:
    metadata:
      labels:
        app: pokeapi-instance2
    spec:
      containers:
      - name: pokeapi
        image: pokeapi:0.1
        ports:
        - containerPort: 80
        env:
        - name: POKEDEX_NAME
          value: "Instance2Pokedex"
        - name: POKEDEX_START_NUMBER
          value: "152"
        - name: POKEDEX_END_NUMBER
          value: "300"
